version: '3'
services:
  igma-postgres-test:
    image: postgres:13-alpine
    container_name: igma-postgres-test
    env_file:
      - .env.test
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - 2345:5432
    volumes:
      - ~/data/igma/postgres-test:/var/lib/postgresql/data
    command: postgres -p ${POSTGRES_PORT}
      
  igma-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: igma-test
    depends_on:
      - igma-postgres-test
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
    working_dir: /usr/src/
    command: bash -c "npm run test"
    env_file:
      - .env.test
    environment:
      NODE_ENV: test
